// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rastreamentoWorkshopAPI.Data;

#nullable disable

namespace rastreamentoWorkshopAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("rastreamentoWorkshopAPI.AtaColaborador", b =>
                {
                    b.Property<int>("AtaWorkshopId")
                        .HasColumnType("int");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.HasKey("AtaWorkshopId", "ColaboradorId");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("AtaColaboradores");
                });

            modelBuilder.Entity("rastreamentoWorkshopAPI.AtaWorkshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Atas");
                });

            modelBuilder.Entity("rastreamentoWorkshopAPI.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("rastreamentoWorkshopAPI.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("rastreamentoWorkshopAPI.AtaColaborador", b =>
                {
                    b.HasOne("rastreamentoWorkshopAPI.AtaWorkshop", "AtaWorkshop")
                        .WithMany("AtaColaboradores")
                        .HasForeignKey("AtaWorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rastreamentoWorkshopAPI.Colaborador", "Colaborador")
                        .WithMany("AtaColaboradores")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtaWorkshop");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("rastreamentoWorkshopAPI.AtaWorkshop", b =>
                {
                    b.HasOne("rastreamentoWorkshopAPI.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("rastreamentoWorkshopAPI.AtaWorkshop", b =>
                {
                    b.Navigation("AtaColaboradores");
                });

            modelBuilder.Entity("rastreamentoWorkshopAPI.Colaborador", b =>
                {
                    b.Navigation("AtaColaboradores");
                });
#pragma warning restore 612, 618
        }
    }
}
